`timescale 1ns / 1ps

////////////////////////
// This file was automatically generated by CATE
// Comments and Notes: 
////////////////////////

module adder_4bit_sim; //no ports to test module

    // declare inputs and outputs for your module
    // can be the same names as the ports of the module under test
    logic [3:0] A;
    logic [3:0] B;
    logic [3:0] S; 
    logic Cin,Cout;
    
    //Instantiate your module undertest
    Adder_4bit my_adder (  .A(A), .B(B), .Cin(Cin), .S(S), .Cout(Cout)  );

    //list your test cases
    initial 
        begin
        A = 0000; B = 0001; Cin = 0;
        #10
        
	// THIS MAY NOT BE CORRECT...!
        A = 1111; B = 0001; Cin = 0;
        #10

        A = 0011; B = 0001; Cin = 0;
        #10

       $display("Finished");  
      end                                 
    
endmodule

